// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjQ78X7RVprecseV3HoTPFDUn067yCrc',
    appId: '1:775315872805:web:5801d982945193e99433cc',
    messagingSenderId: '775315872805',
    projectId: 'notes-app-flutter-44c3e',
    authDomain: 'notes-app-flutter-44c3e.firebaseapp.com',
    storageBucket: 'notes-app-flutter-44c3e.appspot.com',
    measurementId: 'G-WPV74DZG0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLJHKoNYEGHSv-NWO6YOXyZy1H-OELu0',
    appId: '1:775315872805:android:8d3add019eea0fa29433cc',
    messagingSenderId: '775315872805',
    projectId: 'notes-app-flutter-44c3e',
    storageBucket: 'notes-app-flutter-44c3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxs1HIpKTELYHmv5OKYuTB8iQpw7Yi6I',
    appId: '1:775315872805:ios:1c6c6ff3c0fb19b29433cc',
    messagingSenderId: '775315872805',
    projectId: 'notes-app-flutter-44c3e',
    storageBucket: 'notes-app-flutter-44c3e.appspot.com',
    iosBundleId: 'com.example.notesAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCxs1HIpKTELYHmv5OKYuTB8iQpw7Yi6I',
    appId: '1:775315872805:ios:f82b51a729b6e3d29433cc',
    messagingSenderId: '775315872805',
    projectId: 'notes-app-flutter-44c3e',
    storageBucket: 'notes-app-flutter-44c3e.appspot.com',
    iosBundleId: 'com.example.notesAppUi.RunnerTests',
  );
}
